services:
  # Receives the RTMP stream from PS5 and serves it to re-streaming clients
  # Stats UI: http://localhost:8081/
  # RTMP ingest/output: rtmp://localhost:1935/app/<stream-key>
  nginx-rtmp:
    image: "enixcoda/nginx-rtmp"
    restart: always
    ports:
      - "8081:80"    # HTTP stats page
      - "1935:1935"  # RTMP stream ingest and output

  # Hijacks DNS for contribute.live-video.net to redirect PS5 stream to nginx-rtmp
  # DNS service: udp://localhost:53
  # dnsmasq Web UI: http://localhost:8080/
  dnsmasq:
    image: "enixcoda/dnsmasq"
    restart: always
    ports:
      - "53:53/udp"  # DNS queries from PS5
      - "8080:8080"  # dnsmasq web UI
