services:
  nginx-rtmp:
    image: "enixcoda/nginx-rtmp"
    restart: always
    ports:
      - "8081:80"
      - "1935:1935"
  dnsmasq:
    image: "enixcoda/dnsmasq"
    restart: always
    ports:
      - "53:53/udp"
      - "8080:8080"
